apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: k8-project
spec:
  selector:
    matchLabels:
      app: k8-project
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: k8-project
    spec:
      containers:
        - name: k8-project
          image: vishalkumar392/k8-project:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster